# Generated by Django 5.2.5 on 2025-09-06 21:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('patente', models.TextField(blank=True, null=True)),
                ('mail', models.TextField(unique=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'conductor',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('correo', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'coordinador',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lugar', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'destino',
                'ordering': ('lugar',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('salida', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'origen',
                'ordering': ('salida',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('form_nombres', models.TextField()),
                ('form_apellidos', models.TextField()),
                ('form_correo', models.TextField(blank=True, null=True)),
                ('form_telefono', models.TextField()),
                ('pasajeros', models.SmallIntegerField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('idioma_detectado', models.CharField(blank=True, max_length=8, null=True)),
                ('raw_form', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('NUEVA', 'NUEVA'), ('EN_REVISION', 'EN_REVISION'), ('RECHAZADA', 'RECHAZADA'), ('CONFIRMADA', 'CONFIRMADA')], default='NUEVA', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destino', models.ForeignKey(blank=True, db_column='destino_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudes_destino', to='app.destino')),
                ('origen', models.ForeignKey(blank=True, db_column='origen_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudes_origen', to='app.origen')),
            ],
            options={
                'db_table': 'solicitud',
                'ordering': ('-created_at', '-id'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora_agendada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ASIGNADA', 'ASIGNADA'), ('EN_CURSO', 'EN_CURSO'), ('COMPLETADA', 'COMPLETADA'), ('CANCELADA', 'CANCELADA')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, db_column='conductor_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas', to='app.conductor')),
                ('coordinador', models.ForeignKey(blank=True, db_column='coordinador_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas', to='app.coordinador')),
                ('solicitud', models.OneToOneField(db_column='solicitud_id', on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='app.solicitud')),
            ],
            options={
                'db_table': 'reserva',
                'ordering': ('-fecha_hora_agendada', '-id'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tenista',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('correo', models.TextField(blank=True, null=True)),
                ('numero', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'tenista',
                'ordering': ('-id',),
                'managed': True,
                'indexes': [models.Index(fields=['numero'], name='tenista_numero_idx')],
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tenista',
            field=models.ForeignKey(blank=True, db_column='tenista_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudes', to='app.tenista'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['created_at'], name='solicitud_created_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado'], name='solicitud_estado_idx'),
        ),
    ]
