# Generated by Django 5.2.5 on 2025-09-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinador',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='coordinador',
            name='password_hash',
            field=models.CharField(default='', max_length=128),
        ),
    ]
