# Generated by Django 5.2.5 on 2025-09-06 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_coordinador_options_coordinador_password_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinadorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('coordinador', models.ForeignKey(db_column='coordinador_id', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='app.coordinador')),
            ],
            options={
                'db_table': 'coordinador_token',
                'managed': True,
            },
        ),
    ]
