# Generated by Django 5.2.5 on 2025-10-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coordinadortoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='password_hash',
            field=models.CharField(default='', max_length=128),
        ),
    ]
