# Generated by Django 5.2.5 on 2025-10-17 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_conductor_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas', to='app.conductor'),
        ),
    ]
